name: Docker Build, Push & Run in GitHub Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-push-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/project2-project:latest .

      - name: Push Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/project2-project:latest

      - name: Run Docker Container from Docker Hub
        run: |
          docker run -d -p 8000:8000 --env AIPROXY_TOKEN=${{ secrets.AIPROXY_TOKEN }} \
          --name my-running-app ${{ secrets.DOCKER_HUB_USERNAME }}/project2-project:latest
          sleep 10

      - name: Verify Container is Running
        run: |
          docker ps -a  # Check running containers
          docker logs my-running-app  # Check logs for issues

      
      

      - name: Stop & Remove Container
        if: always()
        run: |
          docker stop my-running-app
          docker rm my-running-app
